language: c

os:
  - osx

env:
  - PYCHECKER_VERSION=0.8.19 FIGLEAF_VERSION=0.6.1

compiler:
  - clang

before_install:
  - "brew update 2>&1 > /tmp/brew-update.txt || (cat /tmp/brew-update.txt && false)"

install:
  - brew install
    protobuf
    protobuf-c
    Gsasl
    openssl
    thrift
    ccache
    snappy
    libevent
    python
    bison
  - brew outdated libyaml || brew upgrade libyaml
  - brew outdated json-c || brew upgrade json-c
  - brew outdated boost || brew upgrade boost
  - brew outdated maven || brew upgrade maven
  - brew tap brona/iproute2mac
  - brew install iproute2mac
  - sudo pip install pygresql
  - sudo pip install unittest2 pycrypto lockfile paramiko psi
  - sudo pip install
    "http://sourceforge.net/projects/pychecker/files/pychecker/${PYCHECKER_VERSION}/pychecker-${PYCHECKER_VERSION}.tar.gz/download"
  - sudo pip install
    "http://darcs.idyll.org/~t/projects/figleaf-${FIGLEAF_VERSION}.tar.gz"
  - brew uninstall postgresql

before_script:
  - cd $TRAVIS_BUILD_DIR
  - ./configure

script:
  - make -j$(sysctl -n hw.ncpu)
  - make feature-test
  - make feature-test-clean

branches:
  except:
    - legacy
